### ISSUE TITLE
[E1-S3] This is my third story

### ISSUE THREAD

**Issue by ghackenberg** [fhooe/scrum-with-github-example#2]
**Description:**

TODO

**Tasks:**

- [ ] This is my first simple task
- [ ] This is my second simple task
- [ ] This is my third simple task
